#!/bin/bash

function g_lazy() {
  git add .
  git commit
}

function g_lazy_push() {
  g_lazy
  git push
}

function g_share() {
  git init
  git remote add origin $1
  g_lazy_push
  git push origin master
}

function g_list_remotes() {
  git remote -v show
}

case $1 in
l) g_lazy; exit;;
lazy) g_lazy; exit;;
lp) g_lazy_push; exit;;
lazy-push) g_lazy_push; exit;;
s) g_share $2; exit;;
share) g_share $2; exit;;
lsr) g_list_remotes; exit;;
list-remotes) g_list_remotes; exit;;
esac

git $@
